resolve issue/27
Ourpost/WeChef pull request #28
Opened 2022-12-09 07:47 UTC by yamin-xu

在Desk中增加serial_number欄位，將QRCode網址結尾的id改成serial_number，讓QRCode可以連到顧客點餐頁面。

2022-12-09 09:40 UTC, Jason0227 commented on app/views/desks/_form.html.erb
> +<%= f.hidden_field :serial_number, value: "#{rand(10000000..99999999)}" %>
不懂家加這個隱藏欄位的目的

2022-12-09 09:52 UTC, Jason0227 commented on app/views/menus/order.html.erb
> +<% end %>
這是order的頁面嗎？

2022-12-09 09:56 UTC, Jason0227 commented on config/routes.rb
> +  get '/foods', to: 'menus#order'
想問/foods是哪裡？

2022-12-09 10:00 UTC, Jason0227 commented on app/assets/stylesheets/application.css
> +  margin-top: 2cm;
不懂@media和@page的實體變數為何？

2022-12-09 16:11 UTC, yamin-xu commented on app/views/desks/_form.html.erb
> +<%= f.hidden_field :serial_number, value: "#{rand(10000000..99999999)}" %>
這個就是把serial_number寫進資料庫，用隨機產生一組八位數的數字，而不是讓店家自己填，我之後修改時會再把店家的id加進這組數字中，確保這組數字是不會重複的

2022-12-09 16:12 UTC, yamin-xu commented on app/views/menus/order.html.erb
> +<% end %>
對，就是讓客人點餐的頁面

2022-12-09 16:17 UTC, yamin-xu commented on app/assets/stylesheets/application.css
> +  margin-top: 2cm;
這個可以參考https://medium.com/unalai/%E5%8E%9F%E4%BE%86%E5%89%8D%E7%AB%AF%E7%B6%B2%E9%A0%81%E5%88%97%E5%8D%B0-%E4%B8%8D%E6%98%AF%E5%8F%AA%E8%A6%81-window-print-%E5%B0%B1%E5%A5%BD%E4%BA%86-7af44cacf43e

2022-12-09 17:57 UTC, timwu0109 requested changes
雅閔辛苦了, 抱歉有些問題無法理解在麻煩您幫我們解答一下了

2022-12-09 17:57 UTC, timwu0109 commented on config/routes.rb
> +  get '/foods', to: 'menus#order'
這我覺得我們可以在想想,覺得好像還是可以進到menu index的頁面用判斷的去點菜,但目前這方法的確比較不混亂

2022-12-09 17:57 UTC, timwu0109 commented on Gemfile
> +source 'https://rubygems.org'
抱歉這一段我不太理解 source 的意思 ～在麻煩雅敏幫我解答一下 我看文章 ,是透過 source 還存取Rubygem repository嗎？

2022-12-09 17:57 UTC, timwu0109 commented on app/views/desks/_form.html.erb
> +<%= f.hidden_field :serial_number, value: "#{rand(10000000..99999999)}" %>
我想我跟志雍有一樣的問題,這亂數是要做用在網址上面嗎？還是是幫訂單隨機生成亂數呢？

2022-12-09 17:58 UTC, timwu0109 approved these changes

2022-12-10 02:53 UTC, yamin-xu commented on Gemfile
> +source 'https://rubygems.org'
source是來源，gemfile本來就有的，可能是被我不小心按到刪除了，我這裡只是把source加回去

2022-12-10 02:55 UTC, Jason0227 commented on config/routes.rb
> +  get '/foods', to: 'menus#order'
了解

2022-12-10 02:56 UTC, yamin-xu commented on app/views/desks/_form.html.erb
> +<%= f.hidden_field :serial_number, value: "#{rand(10000000..99999999)}" %>
對，用在網址上的，因為不想讓網址上有id等於多少這種資訊

2022-12-10 02:56 UTC, Jason0227 commented on app/assets/stylesheets/application.css
> +  margin-top: 2cm;
好的

2022-12-10 02:57 UTC, yamin-xu commented on config/routes.rb
> +  get '/foods', to: 'menus#order'
我也覺得兩種方法都可以，但目前這樣做比較方便

2022-12-10 02:57 UTC, Jason0227 commented on app/views/desks/_form.html.erb
> +<%= f.hidden_field :serial_number, value: "#{rand(10000000..99999999)}" %>
了解～我想先把他run起來，之後在修改細節

2022-12-10 02:58 UTC, Jason0227 commented on app/views/menus/order.html.erb
> +<% end %>
了解

2022-12-10 02:59 UTC, Jason0227 approved these changes

2022-12-10 08:40 UTC, Willie542 approved these changes

2022-12-10 08:50 UTC, merged