new model desk
Ourpost/WeChef pull request #7
Opened 2022-12-06 08:46 UTC by wuchengwu

2022-12-06 10:50 UTC, Willie542 approved these changes

2022-12-06 13:21 UTC, Jason0227 commented on app/models/desk.rb
> +  has_many :stores
應該是在 desk 的 model 中 belongs_to :store

2022-12-06 13:26 UTC, Jason0227 commented on db/migrate/20221206081318_create_desks.rb
> +      t.booleen :status
布林值的英文好像是boolean

2022-12-07 00:26 UTC, timwu0109 requested changes
三個問題請再麻煩修正感恩！！

2022-12-07 00:26 UTC, timwu0109 commented on db/migrate/20221206081318_create_desks.rb
> +      t.booleen :status
英文修改後即可,應該是表單上面打錯

2022-12-07 00:26 UTC, timwu0109 commented on app/models/store.rb
> +  belongs_to :desk
store會有很多張餐桌,  所以要改用has many喔

2022-12-07 00:26 UTC, timwu0109 commented on app/models/desk.rb
> +  has_many :stores
這在記得修改

2022-12-07 07:46 UTC, closed without merging